#!/usr/bin/env python3
"""PreCompact hook: generates a HANDOVER doc before context compaction.

Reads the full transcript, sends it to a fresh Claude instance via `claude -p`
to generate a structured handover summary, and saves it.
"""
import json
import os
import subprocess
import sys
from datetime import datetime

def main():
    # Read hook input from stdin
    hook_input = json.load(sys.stdin)
    transcript_path = hook_input.get("transcript_path", "")
    trigger = hook_input.get("trigger", "unknown")

    if not transcript_path or not os.path.exists(transcript_path):
        print(f"No transcript found at {transcript_path}", file=sys.stderr)
        sys.exit(0)

    # Read the transcript
    with open(transcript_path, "r") as f:
        transcript_lines = f.readlines()

    # Extract conversation messages (last 100 exchanges max to stay within limits)
    messages = []
    for line in transcript_lines:
        try:
            entry = json.loads(line.strip())
            messages.append(entry)
        except json.JSONDecodeError:
            continue

    if not messages:
        print("Empty transcript, skipping handover", file=sys.stderr)
        sys.exit(0)

    # Build a condensed transcript for the summarizer
    condensed = []
    for msg in messages[-100:]:
        role = msg.get("role", "unknown")
        if role == "user":
            content = msg.get("content", "")
            if isinstance(content, list):
                text_parts = [p.get("text", "") for p in content if isinstance(p, dict) and p.get("type") == "text"]
                content = "\n".join(text_parts)
            condensed.append(f"USER: {content[:2000]}")
        elif role == "assistant":
            content = msg.get("content", "")
            if isinstance(content, list):
                text_parts = [p.get("text", "") for p in content if isinstance(p, dict) and p.get("type") == "text"]
                content = "\n".join(text_parts)
            condensed.append(f"ASSISTANT: {content[:2000]}")

    transcript_text = "\n---\n".join(condensed[-50:])  # Last 50 exchanges

    # Build the prompt for the summarizer
    prompt = f"""You are generating a handover document for an AI coding assistant session that is about to lose its context.
This document will be the PRIMARY way the next session understands what was happening.

Analyze this conversation transcript and produce a structured handover document.

## Required Sections

### Active Tasks
What was being worked on? What's done, what's in progress, what's blocked?

### Key Decisions Made
Important choices, approaches selected, things explicitly rejected.

### Critical Context
Auth tokens, file paths, connection IDs, environment details — anything the next session needs to know.

### Open Questions
Unresolved issues, things waiting on user input, known blockers.

### Next Steps
Concrete actions the next session should pick up.

---

TRANSCRIPT:
{transcript_text}

---

Generate the handover document now. Be specific and actionable. Include file paths, variable names, and exact values where relevant."""

    # Call claude -p to generate the summary
    try:
        result = subprocess.run(
            ["claude", "-p", prompt],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=hook_input.get("cwd", os.getcwd())
        )

        if result.returncode != 0:
            print(f"claude -p failed: {result.stderr}", file=sys.stderr)
            sys.exit(0)

        handover_content = result.stdout.strip()
    except subprocess.TimeoutExpired:
        print("claude -p timed out after 120s", file=sys.stderr)
        sys.exit(0)
    except FileNotFoundError:
        print("claude CLI not found in PATH", file=sys.stderr)
        sys.exit(0)

    # Save the handover doc
    now = datetime.now()
    timestamp = now.strftime("%Y-%m-%d-%H%M")
    project_dir = hook_input.get("cwd", os.getcwd())
    handover_dir = os.path.join(project_dir, ".claude", "handovers")
    os.makedirs(handover_dir, exist_ok=True)

    filename = f"HANDOVER-{timestamp}.md"
    filepath = os.path.join(handover_dir, filename)

    header = f"""# Session Handover - {now.strftime("%Y-%m-%d %H:%M")}
> Auto-generated by PreCompact hook ({trigger} compaction)
> Transcript: {transcript_path}

"""

    with open(filepath, "w") as f:
        f.write(header + handover_content)

    # Also write/overwrite a "latest" symlink-style file for easy access
    latest_path = os.path.join(handover_dir, "HANDOVER-LATEST.md")
    with open(latest_path, "w") as f:
        f.write(header + handover_content)

    print(f"Handover saved: {filepath}", file=sys.stderr)

    # Return additional context so the compacted session knows about the handover
    output = {
        "hookSpecificOutput": {
            "hookEventName": "PreCompact",
        },
        "systemMessage": f"A handover document was saved at {filepath}. Read this file at the start of the next session for full context."
    }
    print(json.dumps(output))
    sys.exit(0)

if __name__ == "__main__":
    main()
