// V3 Script Collection — all under 2000 chars each
// Run: checkLengths() to verify

const scripts = {

v3_custom_css_102: `(function(){var s=document.createElement('style');s.textContent='body{font-family:"Titillium Web",sans-serif;background:#000;color:#fff;-webkit-font-smoothing:antialiased}.display-font,.df{font-family:"Dosis",sans-serif;line-height:.85;font-weight:700}.vertical-text{writing-mode:vertical-rl;transform:rotate(180deg)}.logo-white{filter:invert(1) brightness(2)}.fine-border{border:1px solid rgba(255,255,255,.15)}.ed-sec{padding:10rem 2.5rem;border-top:1px solid rgba(255,255,255,.15)}.ed-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:2rem}.df{font:700 clamp(4rem,8vw,8rem)/0.85 "Dosis",sans-serif;text-transform:uppercase;letter-spacing:-.02em}.cap-row{border-bottom:1px solid rgba(255,255,255,.1);padding:3rem 1rem;display:flex;align-items:center;justify-content:space-between}.cap-num{font-size:1rem;opacity:.4;font-family:monospace}.cap-title{font:700 clamp(2rem,4vw,3.5rem)/1 "Dosis",sans-serif;text-transform:uppercase}.ed-input{background:transparent;border:none;border-bottom:1px solid rgba(255,255,255,.3);padding:1rem .5rem;color:#fff;font-size:.875rem;text-transform:uppercase;outline:none;width:100%}.ed-btn{padding:1.5rem;border:1px solid #fff;font:700 1.5rem "Dosis",sans-serif;text-transform:uppercase;letter-spacing:.2em;background:transparent;color:#fff;cursor:pointer;width:100%}nav{background:#000!important;border-bottom:1px solid rgba(255,255,255,.15)}';document.head.appendChild(s);})();`,

v3_nav_fix_100: `(function(){if(document.getElementById('v3-nav-links'))return;var cta=document.getElementById('nav-cta-header');if(!cta)return;var d=document.createElement('div');d.id='v3-nav-links';d.style='display:flex;gap:3rem;align-items:center';var links=[['#v3-about','About'],['#v3-caps','Capabilities'],['#v3-mission','Mission'],['#v3-contact','Contact']];d.innerHTML=links.map(function(l){return '<a href="'+l[0]+'" style="font-size:.625rem;text-transform:uppercase;letter-spacing:.25em;font-weight:900;color:#fff;text-decoration:none">'+l[1]+'</a>';}).join('');cta.parentNode.insertBefore(d,cta);})();`,

v3_hero_100: `(function(){if(document.getElementById('v3-hero'))return;var nav=document.getElementById('main-nav');if(!nav)return;var b='https://cdn.prod.website-files.com/620180d2ae54a4a3c90377e0/';var s=document.createElement('section');s.id='v3-hero';s.style='position:relative;min-height:90vh;display:flex;flex-direction:column;justify-content:flex-end;padding:5rem 2.5rem;overflow:hidden;background:#000;margin-top:5rem';s.innerHTML='<div style="position:absolute;top:0;right:0;width:50%;height:100%"><img src="'+b+'67c7d346d46d1682bb421717_Comp3-ezgif.com-optimize(1).gif" style="width:100%;height:100%;object-fit:cover;opacity:.6;filter:grayscale(1) brightness(1.25)"></div><div style="position:relative;z-index:10;max-width:75%"><h1 class="df" style="font-size:clamp(5rem,11vw,12rem);margin:0 0 2rem">Smart<br>Companions<br><span style="color:#eb198b">Built For</span><br>The Real World</h1><div style="display:flex;gap:3rem;align-items:baseline;border-top:1px solid rgba(255,255,255,.15);padding-top:3rem;margin-top:4rem"><p style="font-style:italic;font-size:1.75rem;max-width:32rem;line-height:1.2;color:#d4d4d4;font-weight:300">Intelligent, adaptive, and designed to transform how we experience physical and digital spaces.</p><a href="#v3-contact" style="color:#00afec;font-size:.7rem;text-transform:uppercase;letter-spacing:.3em;font-weight:900;border-bottom:2px solid #00afec;padding-bottom:.5rem;white-space:nowrap;text-decoration:none">Start a Conversation \u2192</a></div></div>';nav.parentNode.insertBefore(s,nav.nextSibling);})();`,

v3_about_100: `(function(){if(document.getElementById('v3-about'))return;var ref=document.getElementById('v3-hero');if(!ref)return;var b='https://cdn.prod.website-files.com/620180d2ae54a4a3c90377e0/';var a=document.createElement('section');a.id='v3-about';a.className='ed-sec';a.innerHTML='<div class="ed-grid"><div style="grid-column:span 8"><h2 class="df" style="font-size:clamp(4rem,8vw,8rem);margin-bottom:4rem">Redefining the<br><span style="font-weight:300;font-style:italic;color:#00afec;text-transform:none">Human-AI Interface</span></h2><p style="font-size:clamp(1.5rem,3vw,2.5rem);font-weight:300;line-height:1.2">Kaleidoco develops adaptive AI companions that interact naturally with people and environments across destinations, venues, and digital platforms.</p></div><div style="grid-column:span 4"><div class="fine-border" style="aspect-ratio:3/4;overflow:hidden"><img src="'+b+'62068335d0435813adc5c6cf_Slice%201.jpg" style="width:100%;height:100%;object-fit:cover;filter:grayscale(1);opacity:.8"></div></div></div>';var sp=document.createElement('section');sp.style='padding:0 2.5rem 10rem';sp.innerHTML='<div style="display:grid;grid-template-columns:8fr 4fr;gap:2rem;min-height:500px"><div class="fine-border" style="overflow:hidden;position:relative"><img src="'+b+'62064684349d2918d1b1d59c_IMAGE5.jpg" style="width:100%;height:100%;object-fit:cover;filter:grayscale(1);opacity:.8"><span style="position:absolute;bottom:2rem;left:2rem;font-size:.625rem;text-transform:uppercase;letter-spacing:.2em;background:rgba(0,0,0,.5);padding:.5rem 1rem">Volume 01 / Spatial Computing</span></div><div class="fine-border" style="overflow:hidden"><img src="'+b+'6206468479c14862aa9f825e_IMAGE4.jpg" style="width:100%;height:100%;object-fit:cover;filter:grayscale(1);opacity:.75"></div></div>';ref.after(a);a.after(sp);})();`,

v3_caps_100: `(function(){if(document.getElementById('v3-caps'))return;var h=document.getElementById('v3-hero');if(!h)return;var ref=h.nextElementSibling;if(ref&&ref.nextElementSibling)ref=ref.nextElementSibling;var s=document.createElement('section');s.id='v3-caps';s.style='padding:10rem 2.5rem;background:#0a0a0a';var it=[['01','Adaptive, Expressive AI Companions','#00afec'],['02','Environmental Intelligence','#eb198b'],['03','Multimodal Presence','#00afec'],['04','Seamlessly Connected Systems','#eb198b']];var rows=it.map(function(i){return '<div class="cap-row"><span class="cap-num">'+i[0]+'</span><h4 class="cap-title">'+i[1]+'</h4><span style="color:'+i[2]+';font-size:1.5rem">\u2197</span></div>';}).join('');s.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:6rem"><h3 class="df" style="font-size:clamp(4rem,8vw,6rem)">Capabilities</h3><span style="font-size:.625rem;letter-spacing:.4em;text-transform:uppercase;color:#6d727c">Core Verticals</span></div><div style="border-top:1px solid rgba(255,255,255,.1)">'+rows+'</div>';if(ref)ref.after(s);else document.body.appendChild(s);})();`,

v3_mission_contact_100: `(function(){if(document.getElementById('v3-mission'))return;var ref=document.getElementById('v3-caps');if(!ref)return;var b='https://cdn.prod.website-files.com/620180d2ae54a4a3c90377e0/';var m=document.createElement('section');m.id='v3-mission';m.style='padding:15rem 2.5rem;border-top:1px solid rgba(255,255,255,.15);display:flex;align-items:center;justify-content:center;text-align:center;background:#000';m.innerHTML='<div style="max-width:72rem"><iconify-icon icon="ri:double-quotes-l" style="font-size:4rem;color:#eb198b;display:block;margin-bottom:3rem"></iconify-icon><blockquote class="df" style="font-size:clamp(2.5rem,5vw,4.5rem)">To bring adaptive, contextual AI into the real world while helping enterprises create more intuitive, connected, and meaningful experiences at scale.</blockquote></div>';var c=document.createElement('section');c.id='v3-contact';c.className='ed-grid';c.style='padding:10rem 2.5rem;align-items:center';c.innerHTML='<div style="grid-column:span 5"><div class="fine-border" style="aspect-ratio:4/5;overflow:hidden"><img src="'+b+'6206843fba98f4bb2ad6e4aa_Want%20to%20talk_.jpg" style="width:100%;height:100%;object-fit:cover;filter:grayscale(1);opacity:.8"></div></div><div style="grid-column:span 7"><h2 class="df" style="font-size:clamp(3rem,6vw,5rem);margin-bottom:1rem">Get in Touch</h2><p style="font-size:1.25rem;font-style:italic;color:#6d727c;margin-bottom:3rem;font-weight:300">Inquire about enterprise integration and bespoke companion development.</p><form style="display:flex;flex-direction:column;gap:2.5rem"><input class="ed-input" type="text" placeholder="NAME"><input class="ed-input" type="email" placeholder="EMAIL ADDRESS"><textarea class="ed-input" rows="4" placeholder="PROJECT BRIEF" style="resize:none"></textarea><button type="submit" class="ed-btn">Send Inquiry</button></form></div>';ref.after(m);m.after(c);})();`,

v3_footer_100: `(function(){if(document.getElementById('v3-footer'))return;var ref=document.getElementById('v3-contact');if(!ref)return;var b='https://cdn.prod.website-files.com/620180d2ae54a4a3c90377e0/';var f=document.createElement('footer');f.id='v3-footer';f.style='padding:5rem 2.5rem;border-top:1px solid rgba(255,255,255,.15);background:#000';f.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-end"><div><img src="'+b+'620bbe1dda4a007560d0f1e6_logo%20horisontal.svg" style="height:1.5rem;width:auto;filter:invert(1) brightness(2);display:block;margin-bottom:2rem"><div style="display:flex;gap:2rem"><a href="#" id="footer-twitter" style="font-size:.625rem;text-transform:uppercase;letter-spacing:.2em;font-weight:900;color:#fff;text-decoration:none">Twitter</a><a href="#" id="footer-linkedin" style="font-size:.625rem;text-transform:uppercase;letter-spacing:.2em;font-weight:900;color:#fff;text-decoration:none">LinkedIn</a><a href="#" id="footer-instagram" style="font-size:.625rem;text-transform:uppercase;letter-spacing:.2em;font-weight:900;color:#fff;text-decoration:none">Instagram</a></div></div><div style="text-align:right"><p style="font-size:.625rem;text-transform:uppercase;letter-spacing:.2em;color:#6d727c;margin-bottom:.5rem">Based in Los Angeles / Worldwide</p><p style="font-size:.625rem;text-transform:uppercase;letter-spacing:.2em;color:rgba(255,255,255,.3)">\u00a9 2024 Kaleidoco Research Corp. All Rights Reserved.</p></div></div>';ref.after(f);})();`

};

function checkLengths() {
  for (const [k, v] of Object.entries(scripts)) {
    console.log(k, v.length, v.length > 2000 ? '❌ OVER' : '✓');
  }
}
checkLengths();
